services:
  php_apache:
    container_name: php-apache
    image: php:8.2-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db